namespace MahjongBuddy.Game.Rule
{
    public enum MjWinningType : byte
    {
        Straight,
        Pong,
        MixPureHand,
        PureHand,
        PureHonorHand,
        SevenPairs,
        ThirteenOrphans,
        LittleDragon,
        BigDragon,
        LittleFourWind,
        BigFourWind,
        AllKong,
        AllHiddenPongAndSelfPick,
        AllTerminal,
        HeavenlyHand,
        EarthlyHand,
        SelfDraw,
        ConcealedHand,
        WinOnLastTile,
        NoFlower,
        OneGoodFlower,
        TwoGoodFlower,
        AllFourFlowerSameType,
        OneGoodWind,
        TwoGoodWind,
        RedDragon,
        GreenDragon,
        WhiteDragon
    }
}
